## Train 5 models based on Seconed Data-preprocessing  using pipeline

In [2]:
import pandas as pd
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
dataset=pd.read_csv("Original_Dataset.csv")
dataset

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4915  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4916                                     Acne             skin_rash   
4917                  Urinary tract infection   burning_micturition   
4918                                Psoriasis             skin_rash   
4919                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  \
0                 skin_rash   nodal_skin_eruptions        dischromic _patches   
1      nodal_skin_eruptions    dischromic _patches                        NaN   
2      nodal_skin_eruptions    dischromic _patches                        NaN   
3                 skin_rash    dischromic _patches                        NaN   
4                 skin_rash   nodal_skin_eruptions                        NaN   
...                     ...                    ...                        ...   
4915               headache                 nausea         spinning_movements   
4916     pus_filled_pimples             blackheads                   scurring   
4917     bladder_discomfort    foul_smell_of urine   continuous_feel_of_urine   
4918             joint_pain           skin_peeling        silver_like_dusting   
4919             high_fever                blister       red_sore_around_nose   

                  Symptom_5            Symptom_6 Symptom_7 Symptom_8  \
0                       NaN                  NaN       NaN       NaN   
1                       NaN                  NaN       NaN       NaN   
2                       NaN                  NaN       NaN       NaN   
3                       NaN                  NaN       NaN       NaN   
4                       NaN                  NaN       NaN       NaN   
...                     ...                  ...       ...       ...   
4915        loss_of_balance         unsteadiness       NaN       NaN   
4916                    NaN                  NaN       NaN       NaN   
4917                    NaN                  NaN       NaN       NaN   
4918   small_dents_in_nails   inflammatory_nails       NaN       NaN   
4919      yellow_crust_ooze                  NaN       NaN       NaN   

     Symptom_9 Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14  \
0          NaN        NaN        NaN        NaN        NaN        NaN   
1          NaN        NaN        NaN        NaN        NaN        NaN   
2          NaN        NaN        NaN        NaN        NaN        NaN   
3          NaN        NaN        NaN        NaN        NaN        NaN   
4          NaN        NaN        NaN        NaN        NaN        NaN   
...        ...        ...        ...        ...        ...        ...   
4915       NaN        NaN        NaN        NaN        NaN        NaN   
4916       NaN        NaN        NaN        NaN        NaN        NaN   
4917       NaN        NaN        NaN        NaN        NaN        NaN   
4918       NaN        NaN        NaN        NaN        NaN        NaN   
4919       NaN        NaN        NaN        NaN        NaN        NaN   

     Symptom_15 Symptom_16 Symptom_17  
0           NaN        NaN        NaN  
1           NaN        NaN        NaN  
2           NaN        NaN        NaN  
3           NaN        NaN        NaN  
4           NaN        NaN        NaN  
...         ...        ...        ...  
4915        NaN        NaN        NaN  
4916        NaN        NaN        NaN  
4917        NaN        NaN        NaN  
4918        NaN        NaN        NaN  
4919        NaN        NaN    

In [4]:
symptoms=[]
## this loop is for creating new column called Symptoms that contain each row's values 
for i in range(len(dataset)):
    value=dataset.iloc[i].values.tolist()## values of each row
    if 0 in value:
         symptoms.append(value[1:value.index(0)]) ## if value is 0 only append data in row that is not 0
    else:
        symptoms.append(value[1:])
        
dataset["Symptoms"]=symptoms
dataset

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4915  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4916                                     Acne             skin_rash   
4917                  Urinary tract infection   burning_micturition   
4918                                Psoriasis             skin_rash   
4919                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  \
0                 skin_rash   nodal_skin_eruptions        dischromic _patches   
1      nodal_skin_eruptions    dischromic _patches                        NaN   
2      nodal_skin_eruptions    dischromic _patches                        NaN   
3                 skin_rash    dischromic _patches                        NaN   
4                 skin_rash   nodal_skin_eruptions                        NaN   
...                     ...                    ...                        ...   
4915               headache                 nausea         spinning_movements   
4916     pus_filled_pimples             blackheads                   scurring   
4917     bladder_discomfort    foul_smell_of urine   continuous_feel_of_urine   
4918             joint_pain           skin_peeling        silver_like_dusting   
4919             high_fever                blister       red_sore_around_nose   

                  Symptom_5            Symptom_6 Symptom_7 Symptom_8  \
0                       NaN                  NaN       NaN       NaN   
1                       NaN                  NaN       NaN       NaN   
2                       NaN                  NaN       NaN       NaN   
3                       NaN                  NaN       NaN       NaN   
4                       NaN                  NaN       NaN       NaN   
...                     ...                  ...       ...       ...   
4915        loss_of_balance         unsteadiness       NaN       NaN   
4916                    NaN                  NaN       NaN       NaN   
4917                    NaN                  NaN       NaN       NaN   
4918   small_dents_in_nails   inflammatory_nails       NaN       NaN   
4919      yellow_crust_ooze                  NaN       NaN       NaN   

     Symptom_9 Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14  \
0          NaN        NaN        NaN        NaN        NaN        NaN   
1          NaN        NaN        NaN        NaN        NaN        NaN   
2          NaN        NaN        NaN        NaN        NaN        NaN   
3          NaN        NaN        NaN        NaN        NaN        NaN   
4          NaN        NaN        NaN        NaN        NaN        NaN   
...        ...        ...        ...        ...        ...        ...   
4915       NaN        NaN        NaN        NaN        NaN        NaN   
4916       NaN        NaN        NaN        NaN        NaN        NaN   
4917       NaN        NaN        NaN        NaN        NaN        NaN   
4918       NaN        NaN        NaN        NaN        NaN        NaN   
4919       NaN        NaN        NaN        NaN        NaN        NaN   

     Symptom_15 Symptom_16 Symptom_17  \
0           NaN        NaN        NaN   
1           NaN        NaN        NaN   
2           NaN        NaN        NaN   
3           NaN        NaN        NaN   
4           NaN        NaN        NaN   
...         ...        ...        ...   
4915        NaN        NaN        NaN   
4916        NaN        NaN        NaN   
4917        NaN        NaN        NaN   
4918        NaN        NaN        NaN   
4919        NaN    

## Data preprocessing

In [6]:
from sklearn.preprocessing import LabelEncoder

column_values=dataset[["Symptom_1","Symptom_2","Symptom_3","Symptom_4","Symptom_5","Symptom_6","Symptom_7","Symptom_8","Symptom_9",
"Symptom_10","Symptom_11","Symptom_12","Symptom_13","Symptom_14","Symptom_15","Symptom_16","Symptom_17"]].values.ravel()
symps=pd.unique(column_values).tolist() 
symps=[i for i in symps if str(i)!="nan"] #

In [14]:
new_data2=pd.DataFrame(columns=dataset.columns,index=dataset.index)
x2=new_data2.drop(["Disease","Symptoms"],axis=1)
columns=x2.columns.tolist()
columns
for i in columns:
       x2[i]=dataset[i].apply(lambda x2: symps.index(x2)+1 if x2 in symps else 0)

encode=LabelEncoder()
y2=dataset["Disease"]
y2=encode.fit_transform(y2)
x2

Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  Symptom_6  \
0             1          2          3          4          0          0   
1             2          3          4          0          0          0   
2             1          3          4          0          0          0   
3             1          2          4          0          0          0   
4             1          2          3          0          0          0   
...         ...        ...        ...        ...        ...        ...   
4915         12         45         16        117         47        118   
4916          2        119        120        121          0          0   
4917         20        122        123        124          0          0   
4918          2         65        125        126        127        128   
4919          2         27        129        130        131          0   

      Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  Symptom_12  \
0             0          0          0           0           0           0   
1             0          0          0           0           0           0   
2             0          0          0           0           0           0   
3             0          0          0           0           0           0   
4             0          0          0           0           0           0   
...         ...        ...        ...         ...         ...         ...   
4915          0          0          0           0           0           0   
4916          0          0          0           0           0           0   
4917          0          0          0           0           0           0   
4918          0          0          0           0           0           0   
4919          0          0          0           0           0           0   

      Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0              0           0           0           0           0  
1              0           0           0           0           0  
2              0           0           0           0           0  
3              0           0           0           0           0  
4              0           0           0           0           0  
...          ...         ...         ...         ...         ...  
4915           0           0           0           0           0  
4916           0           0           0           0           0  
4917           0           0           0           0           0  
4918           0           0           0           0           0  
4919           0           0           0           0           0  

[4920 rows x 17 columns]

## Logisitic Regression

In [108]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
import warnings
from sklearn.exceptions import ConvergenceWarning
warnings.simplefilter("ignore", category=ConvergenceWarning)

pipeline=Pipeline([('scaler',StandardScaler()),('logisticregression',LogisticRegression())])


hyper_parameters={
    'logisticregression__multi_class':['ovr'],
    'logisticregression__solver':['newton-cg', 'lbfgs','saga'],
     'logisticregression__C':[0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000],
}

grid_search=GridSearchCV(pipeline,hyper_parameters,cv=10,verbose=1, n_jobs=-1) 
grid_search.fit(x2,y2)
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation score: ", grid_search.best_score_)
print("Best estimator: ", grid_search.best_estimator_)
final_model= grid_search.best_estimator_




Fitting 10 folds for each of 24 candidates, totalling 240 fits
Best parameters found:  {'logisticregression__C': 1000, 'logisticregression__multi_class': 'ovr', 'logisticregression__solver': 'newton-cg'}
Best cross-validation score:  0.9292682926829269
Best estimator:  Pipeline(steps=[('scaler', StandardScaler()),
                ('logisticregression',
                 LogisticRegression(C=1000, multi_class='ovr',
                                    solver='newton-cg'))])


In [114]:
final_model

Pipeline(steps=[('scaler', StandardScaler()),
                ('logisticregression',
                 LogisticRegression(C=1000, multi_class='ovr',
                                    solver='newton-cg'))])

In [116]:
from sklearn.model_selection import train_test_split,cross_val_score,KFold,ShuffleSplit,LeavePOut


shuffle_split = ShuffleSplit(n_splits=10, test_size=0.3, random_state=0)
k_folds = KFold(n_splits = 10,shuffle=True)
scores = cross_val_score(final_model, x2, y2, cv=10, scoring='accuracy')
scores_shuffle_split = cross_val_score(final_model, x2, y2, cv=shuffle_split, scoring='accuracy')
scores_k_folds = cross_val_score(final_model, x2, y2, cv=k_folds, scoring='accuracy')
# scores = cross_val_score(pipeline, x2, y2, cv=10, scoring='accuracy') 

print("scores cv=10")
print(scores.mean())

print("scores cv=shuffle_split")
print(scores_shuffle_split.mean())
print("scores cv=k_folds")
print(scores_k_folds.mean())


scores cv=10
0.9286585365853661
scores cv=shuffle_split
0.9231029810298104
scores cv=k_folds
0.9258130081300815


In [122]:
X_train,X_test,y_train,y_test=train_test_split(x2,y2,test_size=0.3)

In [124]:
final_model.fit(X_train,y_train)
y_pred=final_model.predict(X_test)

In [126]:
from sklearn.metrics import f1_score,precision_score,classification_report,confusion_matrix, accuracy_score

result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred,zero_division=1)
print("Classification Report:",)
print (result1)
print("Accuracy :",accuracy_score(y_test,y_pred))
print('F1 : ',f1_score(y_test, y_pred, average='weighted'))

Confusion Matrix:
[[24  0  0 ...  0  0  0]
 [ 0 42  0 ...  0  0  0]
 [ 0  0 28 ...  2  0  0]
 ...
 [ 0  0  0 ... 28  0  0]
 [ 0  0  0 ...  0 34  0]
 [ 0  0  0 ...  0  0 42]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.67      0.80        36
           1       0.93      1.00      0.97        42
           2       1.00      0.93      0.97        30
           3       1.00      1.00      1.00        34
           4       1.00      1.00      1.00        37
           5       1.00      1.00      1.00        40
           6       0.87      0.84      0.85        31
           7       0.76      1.00      0.86        28
           8       1.00      1.00      1.00        36
           9       0.97      0.94      0.96        34
          10       1.00      1.00      1.00        38
          11       1.00      1.00      1.00        33
          12       0.88      1.00      0.94        30
          13       0.92      1.00      0.96   

## SVM

In [129]:
from sklearn.svm import SVC

pipeline = Pipeline([('scaler', StandardScaler()), ('svc', SVC())]) 

HyperParametrs= { 'svc__kernel': [ 'poly', 'rbf', 'sigmoid',],}

k_folds = KFold(n_splits = 10,shuffle=True,random_state=10)

grid_search=GridSearchCV(pipeline,HyperParametrs,cv=10, verbose=1, n_jobs=-1)
grid_search.fit(x2, y2)
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation score: ", grid_search.best_score_)
print("Best estimator: ", grid_search.best_estimator_)
final_model= grid_search.best_estimator_

Fitting 10 folds for each of 3 candidates, totalling 30 fits
Best parameters found:  {'svc__kernel': 'rbf'}
Best cross-validation score:  0.9607723577235772
Best estimator:  Pipeline(steps=[('scaler', StandardScaler()), ('svc', SVC())])


In [131]:
shuffle_split = ShuffleSplit(n_splits=10, test_size=0.3, random_state=0)
k_folds = KFold(n_splits = 10,shuffle=True)
scores = cross_val_score(final_model, x2, y2, cv=10, scoring='accuracy')
scores_shuffle_split = cross_val_score(final_model, x2, y2, cv=shuffle_split, scoring='accuracy')
scores_k_folds = cross_val_score(final_model, x2, y2, cv=k_folds, scoring='accuracy')
# scores = cross_val_score(pipeline, x2, y2, cv=10, scoring='accuracy') 

print("scores cv=10")
print(scores.mean())

print("scores cv=shuffle_split")
print(scores_shuffle_split.mean())
print("scores cv=k_folds")
print(scores_k_folds.mean())


scores cv=10
0.9607723577235772
scores cv=shuffle_split
0.9365176151761517
scores cv=k_folds
0.9353658536585365


In [145]:
X_train,X_test,y_train,y_test=train_test_split(x2,y2,test_size=0.3)
final_model.fit(X_train,y_train)
y_pred=final_model.predict(X_test)

In [147]:
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred,zero_division=1)
print("Classification Report:",)
print (result1)
print("Accuracy :",accuracy_score(y_test,y_pred))
print('F1 : ',f1_score(y_test, y_pred, average='weighted'))

Confusion Matrix:
[[40  0  0 ...  0  0  0]
 [ 0 37  0 ...  0  0  0]
 [ 0  0 37 ...  3  0  0]
 ...
 [ 0  0  0 ... 37  0  0]
 [ 0  0  0 ...  0 44  0]
 [ 0  0  0 ...  0  0 29]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.95      1.00      0.97        37
           2       0.82      0.93      0.87        40
           3       1.00      1.00      1.00        39
           4       1.00      0.00      0.00        45
           5       1.00      0.97      0.99        39
           6       1.00      1.00      1.00        36
           7       0.90      1.00      0.95        28
           8       1.00      1.00      1.00        43
           9       0.95      0.97      0.96        39
          10       1.00      1.00      1.00        32
          11       1.00      1.00      1.00        38
          12       1.00      1.00      1.00        30
          13       0.97      1.00      0.99   

## Random Forest 

In [150]:
from sklearn.ensemble import RandomForestClassifier

pipeline = Pipeline([('scaler', StandardScaler()), ('randomforest', RandomForestClassifier())]) 


Hyper_paramters={'randomforest__n_estimators':[10,20,30,40,50,60,70,80,90,100,200,300,400],
                 'randomforest__max_depth':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
                'randomforest__min_samples_leaf':[2,3,4,5,6]}
#Define the five fold Cross Validation max_features
Tree_Gridsearch_paramters=GridSearchCV(pipeline,Hyper_paramters,n_jobs=-1,cv=10,verbose=1)
Tree_Gridsearch_paramters.fit(x2,y2)

#Print the best hyper paramters combination for the best model
print ("The best paramter combination is ",Tree_Gridsearch_paramters.best_params_)
print("Best estimator : ",Tree_Gridsearch_paramters.best_estimator_)

print("The best AUC score was ",Tree_Gridsearch_paramters.best_score_)
final_model= grid_search.best_estimator_

Fitting 10 folds for each of 1300 candidates, totalling 13000 fits
The best paramter combination is  {'randomforest__max_depth': 11, 'randomforest__min_samples_leaf': 2, 'randomforest__n_estimators': 50}
Best estimator :  Pipeline(steps=[('scaler', StandardScaler()),
                ('randomforest',
                 RandomForestClassifier(max_depth=11, min_samples_leaf=2,
                                        n_estimators=50))])
The best AUC score was  1.0


In [152]:
shuffle_split = ShuffleSplit(n_splits=10, test_size=0.3, random_state=0)
k_folds = KFold(n_splits = 10,shuffle=True)
scores = cross_val_score(final_model, x2, y2, cv=10, scoring='accuracy')
scores_shuffle_split = cross_val_score(final_model, x2, y2, cv=shuffle_split, scoring='accuracy')
scores_k_folds = cross_val_score(final_model, x2, y2, cv=k_folds, scoring='accuracy')
# scores = cross_val_score(pipeline, x2, y2, cv=10, scoring='accuracy') 

print("scores cv=10")
print(scores.mean())

print("scores cv=shuffle_split")
print(scores_shuffle_split.mean())
print("scores cv=k_folds")
print(scores_k_folds.mean())

scores cv=10
0.9607723577235772
scores cv=shuffle_split
0.9365176151761517
scores cv=k_folds
0.9416666666666668


In [154]:
X_train,X_test,y_train,y_test=train_test_split(x2,y2,test_size=0.3)
final_model.fit(X_train,y_train)
y_pred=final_model.predict(X_test)

In [156]:
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred,zero_division=1)
print("Classification Report:",)
print (result1)
print("Accuracy :",accuracy_score(y_test,y_pred))
print('F1 : ',f1_score(y_test, y_pred, average='weighted'))

Confusion Matrix:
[[34  0  0 ...  0  0  0]
 [ 0 37  0 ...  0  0  0]
 [ 0  0 30 ...  1  0  0]
 ...
 [ 0  0  0 ... 45  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 34]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        34
           1       0.95      1.00      0.97        37
           2       0.88      0.97      0.92        31
           3       1.00      1.00      1.00        35
           4       0.46      1.00      0.63        34
           5       1.00      0.95      0.97        39
           6       1.00      1.00      1.00        36
           7       0.91      1.00      0.95        39
           8       1.00      1.00      1.00        27
           9       0.93      0.98      0.95        42
          10       1.00      1.00      1.00        36
          11       1.00      1.00      1.00        38
          12       1.00      1.00      1.00        36
          13       0.94      1.00      0.97   

## KNN

In [243]:
from sklearn.neighbors import KNeighborsClassifier


pipeline = Pipeline([('scaler', StandardScaler()), ('knn', KNeighborsClassifier())])

HyperParametrs={
    'knn__n_neighbors':range(19,150,2),         
    'knn__algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']
   }


               #    'weights' : ['uniform','distance'],
               # 'metric' : ['minkowski','euclidean','manhattan'],
               #  'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']
grid_search = GridSearchCV(pipeline, HyperParametrs, cv=10, verbose=1, n_jobs=-1)
grid_search.fit(x2, y2)
print("Best parameters found: ", grid_search.best_params_)
print("Best estimator : ",grid_search.best_estimator_)
print("The best AUC score was ",Tree_Gridsearch_paramters.best_score_)
final_model= grid_search.best_estimator_

Fitting 10 folds for each of 264 candidates, totalling 2640 fits
Best parameters found:  {'knn__algorithm': 'auto', 'knn__n_neighbors': 19}
Best estimator :  Pipeline(steps=[('scaler', StandardScaler()),
                ('knn', KNeighborsClassifier(n_neighbors=19))])
The best AUC score was  1.0


In [245]:
shuffle_split = ShuffleSplit(n_splits=10, test_size=0.3, random_state=0)
k_folds = KFold(n_splits = 10,shuffle=True)
scores = cross_val_score(final_model, x2, y2, cv=10, scoring='accuracy')
scores_shuffle_split = cross_val_score(final_model, x2, y2, cv=shuffle_split, scoring='accuracy')
scores_k_folds = cross_val_score(final_model, x2, y2, cv=k_folds, scoring='accuracy')
# scores = cross_val_score(pipeline, x2, y2, cv=10, scoring='accuracy') 

print("scores cv=10")
print(scores.mean())

print("scores cv=shuffle_split")
print(scores_shuffle_split.mean())
print("scores cv=k_folds")
print(scores_k_folds.mean())

scores cv=10
0.978048780487805
scores cv=shuffle_split
0.9676151761517616
scores cv=k_folds
0.9813008130081302


In [253]:
X_train,X_test,y_train,y_test=train_test_split(x2,y2,test_size=0.3)
final_model.fit(X_train,y_train)
y_pred=final_model.predict(X_test)

In [255]:
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred,zero_division=1)
print("Classification Report:",)
print (result1)
print("Accuracy :",accuracy_score(y_test,y_pred))
print('F1 : ',f1_score(y_test, y_pred, average='weighted'))

Confusion Matrix:
[[33  0  0 ...  0  0  0]
 [ 0 41  0 ...  0  0  0]
 [ 0  0 29 ...  2  0  0]
 ...
 [ 0  0  0 ... 42  0  0]
 [ 0  0  0 ...  0 42  0]
 [ 0  0  0 ...  0  0 39]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        33
           1       1.00      1.00      1.00        41
           2       0.76      0.94      0.84        31
           3       1.00      1.00      1.00        37
           4       1.00      1.00      1.00        51
           5       1.00      0.94      0.97        32
           6       1.00      1.00      1.00        25
           7       1.00      1.00      1.00        36
           8       0.93      0.90      0.92        31
           9       0.91      0.91      0.91        33
          10       1.00      1.00      1.00        33
          11       1.00      1.00      1.00        36
          12       0.94      1.00      0.97        31
          13       1.00      1.00      1.00   

 ## Decision Tree

In [324]:
from sklearn import tree
pipeline = Pipeline([('scaler', StandardScaler()), ('decisiontree',tree.DecisionTreeClassifier())])

Hyper_paramters={'decisiontree__max_depth':[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],
                }
grid_search=GridSearchCV(pipeline,Hyper_paramters,cv=10,verbose=1,n_jobs=-1)
grid_search.fit(x2,y2)
print("Best peramters combination is ")
print(grid_search.best_params_)
print("Best Estimator ")
print(grid_search.best_estimator_)
print("Best cross-validation score:  ")
print(grid_search.best_score_)
final_model=grid_search.best_estimator_

Fitting 10 folds for each of 16 candidates, totalling 160 fits
Best peramters combination is 
{'decisiontree__max_depth': 20}
Best Estimator 
Pipeline(steps=[('scaler', StandardScaler()),
                ('decisiontree', DecisionTreeClassifier(max_depth=20))])
Best cross-validation score:  
0.9493902439024389


In [326]:
shuffle_split = ShuffleSplit(n_splits=10, test_size=0.3, random_state=0)
k_folds = KFold(n_splits = 10,shuffle=True)
scores = cross_val_score(final_model, x2, y2, cv=10, scoring='accuracy')
scores_shuffle_split = cross_val_score(final_model, x2, y2, cv=shuffle_split, scoring='accuracy')
scores_k_folds = cross_val_score(final_model, x2, y2, cv=k_folds, scoring='accuracy')
# scores = cross_val_score(pipeline, x2, y2, cv=10, scoring='accuracy') 

print("scores cv=10")
print(scores.mean())

print("scores cv=shuffle_split")
print(scores_shuffle_split.mean())
print("scores cv=k_folds")
print(scores_k_folds.mean())

scores cv=10
0.9359756097560975
scores cv=shuffle_split
0.9951219512195122
scores cv=k_folds
0.9621951219512195


In [328]:
X_train,X_test,y_train,y_test=train_test_split(x2,y2,test_size=0.3)
final_model.fit(X_train,y_train)
y_pred=final_model.predict(X_test)

In [330]:
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred,zero_division=1)
print("Classification Report:",)
print (result1)
print("Accuracy :",accuracy_score(y_test,y_pred))
print('F1 : ',f1_score(y_test, y_pred, average='weighted'))

Confusion Matrix:
[[36  0  0 ...  0  0  0]
 [ 0 37  0 ...  0  0  0]
 [ 0  0 44 ...  0  0  0]
 ...
 [ 0  0  0 ... 41  0  0]
 [ 0  0  0 ...  0 29  0]
 [ 0  0  0 ...  0  0 25]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       1.00      1.00      1.00        37
           2       1.00      1.00      1.00        44
           3       1.00      1.00      1.00        35
           4       1.00      1.00      1.00        34
           5       1.00      1.00      1.00        41
           6       1.00      1.00      1.00        39
           7       1.00      1.00      1.00        35
           8       1.00      1.00      1.00        41
           9       1.00      1.00      1.00        33
          10       1.00      1.00      1.00        32
          11       1.00      1.00      1.00        39
          12       1.00      1.00      1.00        37
          13       1.00      1.00      1.00   